ALTER TABLE offers ADD COLUMN IF NOT EXISTS accepted_at TIMESTAMP WITH TIME ZONE NULL;
ALTER TABLE offers ADD COLUMN IF NOT EXISTS buyer_rating VARCHAR(10) NULL;
ALTER TABLE offers ADD COLUMN IF NOT EXISTS seller_rating VARCHAR(10) NULL;