# Development environment properties (Local Docker Database)
app.baseUrl=http://localhost:8080/webapp

database.jdbc.url=jdbc:postgresql://localhost/paw
database.jdbc.username=postgres
database.jdbc.password=postgres
