# Development environment properties (Local Docker Database)
app.baseUrl=http://localhost:8080/webapp

database.jdbc.url=jdbc:postgresql://localhost/paw
database.jdbc.username=postgres
database.jdbc.password=postgres

# Mail
mail.host=smtp.gmail.com
mail.port=587
mail.username=swappr.marketplace@gmail.com
mail.password=rkru owjj ijso ildb
mail.from=swappr.marketplace@gmail.com
